CREATE DATABASE estoqueProd;
use estoqueProd;
CREATE TABLE produto(
id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME varchar(60) DEFAULT NULL,
PRECO decimal(10,2) DEFAULT NULL,
CATEGORIA varchar(60) DEFAULT NULL,
QUANTIDADE int DEFAULT NULL
)
